apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp-deployment
  labels:
    app: mywebapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec:
      containers:
      - name: mywebapp
        image: pros2018/mywebapp:latest
        ports:
        - containerPort: 7002

---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
  namespace: default
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 7002
    targetPort: 7002
    nodePort: 31001   # Specify the desired node port here
  selector:
    app: mywebapp

---
apiVersion: v1
kind: Service
metadata:
  name: mywebapp-preview-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 7002
    targetPort: 7002
  selector:
    app: mywebapp
